return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "1.0.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 2000,
  height = 16,
  tilewidth = 32,
  tileheight = 32,
  nextobjectid = 280,
  properties = {
    ["music"] = "resources/music/keygen_9000.xm",
    ["px"] = 0,
    ["py"] = 12
  },
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      name = "Ground",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 5,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 2144,
          y = 448,
          width = 1920,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 6496,
          y = 448,
          width = 832,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 4576,
          y = 384,
          width = 320,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 4192,
          y = 448,
          width = 448,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 5920,
          y = 320,
          width = 576,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 2688,
          y = 224,
          width = 224,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 0,
          y = 448,
          width = 960,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 1088,
          y = 448,
          width = 736,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 4832,
          y = 320,
          width = 320,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 5088,
          y = 256,
          width = 320,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 5344,
          y = 192,
          width = 320,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 7488,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 7584,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 7680,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 7872,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 7968,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 8224,
          y = 448,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 8608,
          y = 384,
          width = 64,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 8800,
          y = 224,
          width = 64,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 8992,
          y = 224,
          width = 64,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 9184,
          y = 0,
          width = 64,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 9376,
          y = 448,
          width = 736,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 10272,
          y = 352,
          width = 128,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 10496,
          y = 352,
          width = 128,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 11392,
          y = 128,
          width = 64,
          height = 384,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 10784,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 11232,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 124,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 11648,
          y = 256,
          width = 64,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 125,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 11776,
          y = 320,
          width = 64,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 126,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 11008,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 11520,
          y = 192,
          width = 64,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 12192,
          y = 448,
          width = 288,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 142,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 12544,
          y = 384,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 143,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 12736,
          y = 256,
          width = 608,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 144,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 12736,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 146,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 12928,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 147,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 13280,
          y = 480,
          width = 3552,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 222,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 17056,
          y = 480,
          width = 736,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 269,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 11904,
          y = 384,
          width = 64,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 279,
          name = "",
          type = "Ground",
          shape = "rectangle",
          x = 640,
          y = 384,
          width = 960,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "Checkpoint",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 28,
          name = "",
          type = "Checkpoint",
          shape = "rectangle",
          x = 6688,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 2784,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 2720,
          y = 256,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 3456,
          y = 416,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 4512,
          y = 416,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 4768,
          y = 352,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 5024,
          y = 288,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 5312,
          y = 192,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 5792,
          y = 128,
          width = 576,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 4512,
          y = 256,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 4768,
          y = 192,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 5024,
          y = 128,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 5312,
          y = 160,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 7776,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 8096,
          y = 288,
          width = 32,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 8096,
          y = 64,
          width = 32,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 8896,
          y = 320,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 9504,
          y = 352,
          width = 480,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 10144,
          y = 448,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 10400,
          y = 0,
          width = 32,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 131,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 12064,
          y = 448,
          width = 128,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "",
          type = "Checkpoint",
          shape = "rectangle",
          x = 9600,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 136,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 11552,
          y = 0,
          width = 64,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 137,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 11680,
          y = 0,
          width = 64,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 138,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 11808,
          y = 0,
          width = 64,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 148,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 13344,
          y = 256,
          width = 384,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 12768,
          y = 288,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 8416,
          y = 448,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 192,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 13888,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 193,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 14112,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 194,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 14336,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 213,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 15712,
          y = 448,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 216,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 15936,
          y = 448,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 224,
          name = "",
          type = "Checkpoint",
          shape = "rectangle",
          x = 13376,
          y = 416,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 232,
          name = "",
          type = "Coin",
          shape = "rectangle",
          x = 10432,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 235,
          name = "",
          type = "Coin",
          shape = "rectangle",
          x = 13088,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 241,
          name = "",
          type = "Coin",
          shape = "rectangle",
          x = 4128,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 242,
          name = "",
          type = "Coin",
          shape = "rectangle",
          x = 1280,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 244,
          name = "",
          type = "Coin",
          shape = "rectangle",
          x = 7392,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 245,
          name = "",
          type = "Coin",
          shape = "rectangle",
          x = 2560,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 246,
          name = "",
          type = "Coin",
          shape = "rectangle",
          x = 2336,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 247,
          name = "",
          type = "Coin",
          shape = "rectangle",
          x = 1568,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 249,
          name = "",
          type = "Coin",
          shape = "rectangle",
          x = 5856,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 250,
          name = "",
          type = "Coin",
          shape = "rectangle",
          x = 9280,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 255,
          name = "Goal",
          type = "Checkpoint",
          shape = "rectangle",
          x = 17312,
          y = 416,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 257,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 14784,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 258,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 15008,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 259,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 15232,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 260,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 15392,
          y = 416,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 261,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 16352,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 262,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 16576,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 263,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 16352,
          y = 256,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 265,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 16800,
          y = 256,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 266,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 16576,
          y = 256,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 267,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 16800,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 270,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 11936,
          y = 0,
          width = 32,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 271,
          name = "",
          type = "Spike",
          shape = "rectangle",
          x = 11424,
          y = 0,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 272,
          name = "",
          type = "Coin",
          shape = "rectangle",
          x = 10880,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 275,
          name = "",
          type = "Coin",
          shape = "rectangle",
          x = 14336,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 276,
          name = "",
          type = "Coin",
          shape = "rectangle",
          x = 15296,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 278,
          name = "",
          type = "Coin",
          shape = "rectangle",
          x = 16928,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
